// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum RewardTypes {
  PledgeIncome,
  DirectPromotionIncome,
  DynamicIncome,
  LevelIncome,
  GradedIncome,
  FlashIncome,
  Base,
  RedIncome,
  TSIncome,
  ZSIncome,
  LRIncome
}

enum PlegedStatus {
  Pendding,
  Closed
}
