// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { Administrator } from "./tables/Administrator.sol";
import { PayToken } from "./tables/PayToken.sol";
import { BindRoot } from "./tables/BindRoot.sol";
import { IncomeRate } from "./tables/IncomeRate.sol";
import { Total } from "./tables/Total.sol";
import { Factory } from "./tables/Factory.sol";
import { USDC } from "./tables/USDC.sol";
import { Router } from "./tables/Router.sol";
import { User, UserData } from "./tables/User.sol";
import { UserEx, UserExData } from "./tables/UserEx.sol";
import { Relation, RelationData } from "./tables/Relation.sol";
import { PlegedLog, PlegedLogData } from "./tables/PlegedLog.sol";
import { RewardLog, RewardLogData } from "./tables/RewardLog.sol";
import { BlockIncomeRate, BlockIncomeRateData } from "./tables/BlockIncomeRate.sol";
import { ChangeIncomeRateLog } from "./tables/ChangeIncomeRateLog.sol";
import { ClaimLog, ClaimLogData } from "./tables/ClaimLog.sol";
import { FeeAddress } from "./tables/FeeAddress.sol";
import { PoolAddressesProvider } from "./tables/PoolAddressesProvider.sol";
import { XToken } from "./tables/XToken.sol";
import { Pledging, PledgingData } from "./tables/Pledging.sol";
import { UsersList } from "./tables/UsersList.sol";
import { BlackList } from "./tables/BlackList.sol";
import { TeamList } from "./tables/TeamList.sol";
import { TeamConfig } from "./tables/TeamConfig.sol";
import { ParentIncome, ParentIncomeData } from "./tables/ParentIncome.sol";
import { LevelRedBlackList } from "./tables/LevelRedBlackList.sol";
import { Oper } from "./tables/Oper.sol";
import { OpLog, OpLogData } from "./tables/OpLog.sol";
import { LevelLog, LevelLogData } from "./tables/LevelLog.sol";
